### PR TITLE
Optimize fishschool2

### PR DESCRIPTION
**Pull request by geoffsalmon**
More fishschool optimizations.

The first avoids accessing the GameObject.transform property, which apparently hides a GetComponent call.

The next rearranges ApplyZones to query the octtree only once. A side-affect of this commit is the zones are spherical instead of based on the bounds cube.

The next commit changes each 2D fish prefab to a single gameobject with a single mesh and texture. This avoids creating a lot of gameobjects at runtime and seems to allow better batching.

The last commit removes all the unused fish right textures. The right side of the fish uses the mirrored left texture instead.

### CODE REVIEW

**Comment by Zulban** [comment]
This appears to cause significant changes in fishy movement. This is most clearly demonstrated in the scene "Stuart Tests/collect1". On master they swarm, on your branch they generally diffuse forever.

**Comment by geoffsalmon** [comment]
I fixed that bug I think. The repulsion zone was effectively much larger than it should be because of this line

```
float repulsionSq = radiusOrfOrientation * radiusOfRepulsion;
```

which should have been

```
float repulsionSq = radiusOrfRepulsion * radiusOfRepulsion;
```

Please try it out again.

**Comment by Zulban** [comment]
Hmmm, I never got an email for your reply. I think.

**Comment by geoffsalmon** [comment]
No prob. Have you had a chance to look at how the updated changes perform?

**Comment by Zulban** [comment]
I did, briefly, but I've been busy with school work and work. This tragedy will resolve itself very soon.

**Comment by Zulban** [comment]
Cool, I merged it.

**Pull request merged**
